# Generated by Django 4.2.1 on 2023-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='excel_file',
            field=models.FileField(upload_to='excel_files/%Y/%m/%d/'),
        ),
    ]
