# Generated by Django 4.2.1 on 2023-05-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_scrape', '0002_alter_excelfile_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='file_field',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
