# Generated by Django 4.2.1 on 2023-05-31 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocp_scrape', '0003_remove_excelfile_excel_file_excelfile_file_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.taskresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('django_celery_results.taskresult',),
        ),
    ]
