# Generated by Django 4.2.1 on 2023-05-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_scrape', '0004_extendedtaskresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedTaskResult',
        ),
    ]
