# Generated by Django 4.2.1 on 2023-06-05 22:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocp_scrape', '0007_excelfile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelFile',
            new_name='GeneratedFiles',
        ),
    ]
